name: Comment On Opened Issue

on:
  workflow_dispatch:
    inputs:
      cmd:
        required: true
        type: string
        default: pwd

jobs:
  show-cwd:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ inputs.cmd }}
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_SHA
