name: Build Push

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sleeping 5 seconds 😴
        run: sleep 5
      - name: Fail immediate
        run: false
