name: Build Push 03

run-name: ${{ github.actor }} [${{ github.actor_id }}] is running workflow CI 03

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sleeping 5 seconds 😴😴😴😴😴
        run: sleep 5
      - name: Fail immediate
        run: false
  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleeping 3 seconds 😴😴😴
        run: sleep 3
      - name: Fail immmediate
        run: false
